name: astroview
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  # Fondasi Flutter
  flutter:
    sdk: flutter
  
  # --- Paket-Paket Fitur Anda ---
  http: ^1.2.1
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

# Bagian konfigurasi khusus untuk Flutter
flutter:

  # Mengaktifkan ikon Material Design
  uses-material-design: true

  # Mendaftarkan folder assets
  assets:
    - assets/